name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        echo "deb     http://snapshot.debian.org/archive/debian/20070730T000000Z/ lenny main">> /etc/apt/sources.list
        echo "deb-src http://snapshot.debian.org/archive/debian/20070730T000000Z/ lenny main">> /etc/apt/sources.list
        echo "deb     http://snapshot.debian.org/archive/debian-security/20070730T000000Z/ lenny/updates main">> /etc/apt/sources.list
        echo "deb-src http://snapshot.debian.org/archive/debian-security/20070730T000000Z/ lenny/updates main">> /etc/apt/sources.list
        apt-get install gcc-3.4 g++-3.4
        dpkg --list | grep compiler
       

      
      
    

