name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        sudo apt-get install gcc-3.4 g++-3.4
        dpkg --list | grep compiler
       

      
      
    

